apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -sample

resources:
- ../base

images:
- name: docker.io/zhlhahaha/reqs-payload
  newTag: aarch64-aa0ff73cbf4b218b83e85e4f80eab7591e9dc79c
- name: docker.io/zhlhahaha/runtime-payload
  newName: docker.io/zhlhahaha/runtime-payload
  newTag: kata-containers-b42968014fc99eee53c3070dd1ad6d03ac1f0624-aarch64

patches:
- patch: |-
    - op: replace
      path: /spec/config/runtimeClasses
      value:
      - name: "kata-clh"
        snapshotter: "overlayfs"
      - name: "kata-clh-tdx"
        snapshotter: "overlayfs"
      - name: "kata-qemu"
        snapshotter: "overlayfs"
      - name: "kata-qemu-tdx"
        snapshotter: "overlayfs"
      - name: "kata-qemu-sev"
        snapshotter: "overlayfs"
      - name: "kata-qemu-snp"
        snapshotter: "overlayfs"
    - op: add
      path: /spec/config/defaultRuntimeClassName
      value: "kata-qemu"
    - op: add
      path: /spec/config/debug
      value: false
  target:
    kind: CcRuntime
